"use client";

import {
  AlertCircle,
  AlertTriangle,
  BarChart3,
  Camera,
  Check,
  ChevronRight,
  Copy,
  Download,
  ExternalLink,
  FileText,
  Flame,
  Globe,
  Image,
  Layers,
  Lightbulb,
  Link2,
  ListOrdered,
  Loader2,
  Maximize2,
  MessageCircle,
  Mic,
  Microscope,
  NotebookPen,
  Palette,
  Paperclip,
  Pencil,
  PenLine,
  RefreshCw,
  Repeat2,
  Rocket,
  Search,
  Send,
  Settings,
  Sparkles,
  Square,
  Target,
  Theater,
  ThumbsUp,
  Type,
  Users,
  X,
  Zap,
} from "lucide-react";

const ICONS = {
  AlertCircle,
  AlertTriangle,
  BarChart3,
  Camera,
  Check,
  ChevronRight,
  Copy,
  Download,
  ExternalLink,
  FileText,
  Flame,
  Globe,
  Image,
  Layers,
  Lightbulb,
  Link2,
  ListOrdered,
  Loader2,
  Maximize2,
  MessageCircle,
  Mic,
  Microscope,
  NotebookPen,
  Palette,
  Paperclip,
  Pencil,
  PenLine,
  RefreshCw,
  Repeat2,
  Rocket,
  Search,
  Send,
  Settings,
  Sparkles,
  Square,
  Target,
  Theater,
  ThumbsUp,
  Type,
  Users,
  X,
  Zap,
};

/**
 * Renders a Lucide icon by PascalCase name. Icons must be listed in ICONS above.
 */
export function StudioLucide({ name, size = 16, color = "currentColor", strokeWidth = 2, style, className }) {
  const Cmp = name ? ICONS[name] : null;
  // lucide-react exports ForwardRefs (typeof "object"), not plain functions
  if (Cmp == null) return null;
  return <Cmp size={size} color={color} strokeWidth={strokeWidth} style={style} className={className} aria-hidden />;
}
